# permissions for end users to view configurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: uniflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: configuration-viewer-role
rules:
- apiGroups:
  - uniflow.dev
  resources:
  - configurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uniflow.dev
  resources:
  - configurations/status
  verbs:
  - get
