# permissions for end users to edit revisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: uniflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: revision-editor-role
rules:
- apiGroups:
  - uniflow.dev
  resources:
  - revisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uniflow.dev
  resources:
  - revisions/status
  verbs:
  - get
